server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    servlet:
        session:
            timeout: 1800s
        context-path: /

#数据源配置
spring:
  datasource:
    name: db1
    url: jdbc:mysql://192.168.0.254:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

#redis 这里用1库
  redis:
    database: 1
    host: 192.168.0.204
    password: root123
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    port: 6379
    timeout: 6000ms
  cache:
    redis:
      time-to-live: 60000ms
    cache-names: cache1
  web:
    resources:
      static-locations: classpath:/webapp/
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


#多数据源配置
slave:
  datasource:
    name: db1,db2
    db1:
      url: jdbc:mysql://192.168.0.254:3306/test?serverTimezone=Asia/Shanghai
      username: root
      password: TnorNmQhsXbYLX8uV2WCS6aISDKpU9oT9efxVzNSngJ0gkTNZLNHDxRVUZv/i5gM5iQBAmYMKxZQI4YN35NTBQ==
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

      druid:
        stat-view-servlet:
          enabled: true
        filter:
          config:
            enabled: true
        connection-properties: config.decrypt=true;config.decrypt.key=${public-key1}
        filters: stat,wall.log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    db2:
      url: jdbc:mysql://180.76.103.218:3306/test?serverTimezone=Asia/Shanghai
      username: root
      password: WdAlsp4YWEwl4/j+1RO3TqDqqqeAYHdMRfczeDiOlhDbfu801Fb7+BWD6ZYbPVH37vM20QvuRuxz0JByynwUjg==
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        start-view-servlet:
          enabled: true
        filter:
          config:
            enabled: true
        connection-properties: config.decrypt=true;config.decrypt.key=${public-key2}
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

public-key1: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJFR813V1xKaKzCSwyKu1eTKLb9elUjRc3q+GOJVg5pEuEoqou/xsvURgUO80Wkx0dacLRGR6+6htfD6t8QX7w0CAwEAAQ==
public-key2: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAInrkfj+NG+HcGl7IEP3WFwVrVw4gQ/vVfcbFQSjMl+f8eFjIaMei7Mff/NmGTaAzvxhqdz851ctU3fTI0MC+E8CAwEAAQ==
#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.entity


#日志配置
logging:
  config: classpath:log4j.xml